project:
  type: book
  output-dir: docs
  resources:
    - mathjax/**

book:
  title: "The Manifesto of Categorical Nonsense"
  author: "James R. P. Turesson"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - functors.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: "Palatino, Georgia, serif"
    fontsize: 1.05em
    linestretch: 1.7
    reference-location: margin
    theme:
      - cosmo
      - brand
      - custom.scss
    html-math-method:
      method: mathjax
      url: ./mathjax/tex-chtml.js
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              macros: {
                norm:  ["\\left\\lVert #1 \\right\\rVert", 1],
                abs:   ["\\left\\lvert #1 \\right\\rvert", 1],
                ip:    ["\\langle #1, #2 \\rangle", 2],
                Grp:  "\\operatorname{Grp}",
                AbGrp:  "\\operatorname{AbGrp}",
                Set:  "\\operatorname{Set}",
                Top:  "\\operatorname{Top}",
                Vect:  "\\operatorname{Vect}",
                Ob:  "\\operatorname{Ob}",
                Mor:  "\\operatorname{Mor}",
                dom:  "\\operatorname{dom}",
                cod:  "\\operatorname{cod}",
                id:  "\\operatorname{id}",
                Hom: "\\operatorname{Hom}",
                End: "\\operatorname{End}",
                Spec:  "\\operatorname{Spec}",
                supp:  "\\operatorname{supp}",
                RR:    "\\mathbb{R}",
                CC:    "\\mathbb{C}",
                ZZ:    "\\mathbb{Z}",
                Hzero: "H^1_0",
              }
            }
          };
          </script>
#  pdf:
#    documentclass: scrbook
#    papersize: a4
#    geometry:
#      - margin=3.2cm
#    include-in-header:
#      - macros.tex
#    keep-tex: true

