---
title: "Preface"
toc: true
toc-location: body
toc-title: "On this page"
toc-depth: 2
---

# Preface {.unnumbered}

This is a collection of notes, observations and references that I originally made throughout my time as a masters student at the University of Bonn. Born out of my lack of understanding of category theory, I felt utterly blindsided by an enigmatic and everpresent collection of ideas and results which presented itself in virtually every algebraic course which I undertook. Indeed during the first tutorial I attended during my graduate studies, the tutor proclaimed that one of the problems of the first exercise sheets is simply solved by "abstract nonsense", which was rather upsetting to myself as I had been struggling with that particular problem the entire week. However, in the time since this frightening initial exposure, category theory has cemented itself as a central column in my understanding of any research within algebra. 

The book will introduce categories and discuss the various important types categories which one might encounter. It is intended to be both a suitable introduction to the student who is towards the end of their undergraduate studies, and a compendium of different category theoretical structures, objects and diagrams, where they occur and which properties they may satisfy, suitable for the mathematician who wants to brush up on particular structures.

Throughout the text I shall ensure to give references and direct the reader to sources which they might find useful. You are free to share this resource wherever you see fit under the condition that it is distributed free of charge and furthers the diversification of the mathematics community. In that vein, I welcome any suggestions and comments on the work, these are after all not ideas that belong to myself, but meerly a regurgitation of of those which were fed to me at various points.

::: {.text-end}
— *J. R. P. Turesson, Bonn, August 2026*
:::
