# Introduction to Categories

The notion of a category was popularised by Eilenberg and MacLane and is motivated by several examples of essential structures and their associated maps such as groups and group homomorphisms or vector spaces and linear transformations [@EilMac45]. However, as outlined in the introduction to the paper, one of the main interests in developing this theory lies in studying functors (maps between categories) and maps between functors. We may already be getting a head of ourselves here and so I would like to focus on a structure which many mathematicians become familiar with during their undergraduate degrees, namely the group. The purpose here will be think about the fundamental features of the structures involved in group theory and how they me abstracted. Furthermore, we introduce a concept which is fundamental to category theory; properties of maps may not be checked element wise in the general setting. This requires a shift in perspective, away from studying maps individually and towards studying them in relation to other maps.

## Abstracting groups

First we recall the definition of the group. We will later abuse the notation, as is usual, and refer to both the underlying set and the group itself by the same symbol.

::: {#def-group}
## Group
A group is a set $G$ equipped with a binary operation $\ast:G\times G\to G$ such that the following axioms are satisfied.

:::{.axioms}
#. There exists an element $e\in G$ such that $e\ast g=g=g\ast e$ for any element $g\in G$.
#. For each element $g\in G$ there exists an element $g^{-1}\in G$ such that $g\ast g^{-1}=e=g^{-1}\ast g$.
#. For any elements $\alpha,\beta,\gamma\in G$ we have
$$\alpha\circ (\beta\circ \gamma)=(\alpha \circ\beta )\circ \gamma$$
:::

:::

Although the group itself is initially an area of interest for the young mathematician, the simple axioms giving rise to properties such as uniqueness of identities and inverses, one realises rather swiftly that the beauty of the theory of groups lie in the study of the relation between groups. This work is done by group homomorphisms, the mappings associated to group theory. This is a feature throughout the various fields of study for different algebraic structures, it is the maps in and out of the structures which give them meaning, we are studying the interstructure relationships through the mappings.

:::{#def-grouphom}
## Group homomorphism
Let $G$ and $H$ be groups, then we call a map $\phi: G\to H$ a group homomorphism if for any $g,h\in G$ we have
$$\phi(g\ast_G h)= \phi(g)\ast_H\phi (h)$$
:::

Group homomorphisms are verily stronger than a simple map on the underlying sets, as they ensure that the group operation is respected. It carries the strucure of the domain in a nice manner, mapping the domain's identity to the identity of the codomain, and similarly bringing inverses to inverses in the obvious manner. Naturally the simplest group homomorphism we can create for any group $G$ is probably the identity which maps a group $G$ to itself.

::: {#exm-identitygrouphom}
## The identity homomorphism
Let $G$ be a group and consider tha mapping $\id_G :G\to G$ which is defined by $g\mapsto g$. This clearly forms a group homomorphism as both domain and codomain posess the same group operation. 
:::

Every structure should give rise to identity maps, the example above gives each group an identity homomorphism, for vector spaces we have the identity matrices, for topological spaces we have the identity map. They all posses the same intuitive quality, identities change nothing, the structure which arises from the image of the identity is the same as the structure of the domain on which it acts. This notion becomes more tangible when we discuss about the composition of maps. Note that a group homomorphism $\phi$ has a source group $G$ and a target group $H$ called the domain and codomain respectively, and these groups encode which other homomorphisms can be used in composition with $\phi$. We denote the domain of a group homomorphism $\phi$ by $\dom\phi$ and the codomain by $\cod\phi$. Let $\Hom_{\Grp}$ denote the class of all group homomorphism, and let $\Hom_{\Grp} \times_{\Grp}\Hom_{\Grp}$ denote the set
$$\{(\psi, \phi)\in \Hom_{\Grp} \times\Hom_{\Grp}\,\vert\, \cod\phi=\dom\psi \}$$
Then we define the composition operation on the class of group homomorphisms.

::: {#def-grouphomcomp}
## Composition of group homomorphism
The class function $\circ : \Hom_{\Grp} \times_{\Grp}\Hom_{\Grp}\to \Hom_{\Grp}$ defined by $(\psi,\phi)\mapsto [x\mapsto \psi (\phi(x))]$ is called the composition map of group homomorphisms. We denote $\circ (\psi, \phi)$ by $\psi\circ\phi$.
:::

I agree with the sentient that the tedium here is excesssive and is not necessary in forming an understanding of group theory, however, I believe this view of composition will aid in understanding the generalisation which we present in category theory. The mappings in category theory (which will be called morphisms) are in general far more abstract. We might not be able to speak of images of single points in a domain, nor would we be able to speak of if a point is a member of the kernel or not. These abstracted properties are instead presented by the structures of morphisms in relation to each other and through composition. That being said, we will examine how the composition of group homomorphisms work by doing it element wise.

::: {#exm-identitygrouphomcomp}
## Composition with identity homomorphism
Let $\phi:G\to H$ be a group homomorphism, and consider the following compositions with the identity $\id_G$ and the identity $\id_H$
$$\phi\circ\id_G(g)=\phi(\id_G(g))=\phi(g)$$
and similarly we have that
$$\id_H\circ \phi(g)=\id_G(\phi(g))=\phi(g)$$
:::

The example above demonstrates that if a group homomorphism $\phi$ has domain $G$ then $\phi=\phi\circ \id_G$ and if it has codomain $H$ then $\phi = \id_H\circ \phi$. We can always reduce any well defined composition with an identity, this will be a fundamental concept in the theory of categories. This is particularly useful when we compose a map with its inverse, which may of course not always exist. We usually learn that a group isomorphism is a homomorphism which is bijective. However, when working with categories we want to distance ourselves from thinking about the images of elements and think of the possible interactions of the map in question with other maps with which it can be composed. Therefore, we think of right and left inverses, and a map admits an inverse if it admits both a right and a left inverse. 

::: {#def-inversegrouphom}
## Inverse homomorphism
Let $\phi:G\to H$ be a group homomorphism. A group homomorphism $\psi: H\to G$ is called a right inverse of $\phi$ if $\phi\circ \psi=\id_H$ and it is called a left inverse of $\phi$ if $\phi\circ\psi=\id_G$. Furthermore, $\psi$ is called an inverse of $\phi$ if it is both a right and left inverse of $\phi$. 
:::

Usually we are introduced to group isomorphisms as bijective group homomorphisms, however here we will adopt the view which will give rise to the definition of the general isomorphism in the theory of categories. Instead of considering injectivity and surjectivity of a group isomorphism we will consider inverses.

::: {#prp-inversegivesiso}
A group homomorphism $\phi : G\to H$ admits an inverse $\psi: H\to G$ if and only if it is an isomorphism.
:::

::: {.proof}
Suppose that $\psi$ is an inverse of $\phi$. Let $h\in H$, we will show that there exists an element $g\in G$ such that $\phi(g)=h$. Note that
$$h=\id_H(h)=\phi\circ\psi (h)$$
and as $\psi(h)\in G$ we have that $\phi$ is surjective. Consider now two elements $g_1, g_2\in G$ such that $\phi(g_1)=\phi(g_2)$, we will now show that we must have $g_1=g_2$. We have
$$g_1=\id_G (g_1)=\psi\circ\phi(g_1)=\psi(\phi(g_1))=\psi(\phi(g_2))=\psi\circ\phi(g_2)=\id_G(g_2)=g_2$$
and so it follows that $\phi$ is injective.

Conversely, suppose that $\phi$ is an isomorphism, which is that it is both surjective and injective. Let us consider the map $\psi :H\to G$ defined by sending $h\in H$ to the unique element in its preimage under $\phi$, uniqueness follows from injectivity and existence follows from surjectivity. Then 
$\phi\circ \psi(h)=h$ and so $\phi\circ \psi=\id_H$, further, $\psi\circ \phi(g)=g$ and so $\psi\circ \phi=\id_G$. Now $\psi$ is an inverse of $\phi$.
:::

This will likely not have been anything new to the reader, however if you have not been exposed to category theory before then this shift in perspective towards examining properties of maps by how they compose with others is going to aid in abstracting the essence of what gives meaning to all agebraic structures. More generally than the result above we have that a group homomorphism is injective if and only if it admits a left inverse and it is surjective if and only if it admits a right inverse.

Finally, I would like to bring our attention to subgroups. Recall that a subset $H$ of a group $G$ is called a subgroup if $H$ forms a group with respect to the group operation $\ast_G$. Equivalently, a nonempty subset $H$ is a subgroup if it is closed under $\ast_G$ and inverses. Generally, algebraic structures have underlying sets and so a substructure $B$ of an algebraic structure $A$ is just a subset $B$ such that when endowed with the same operations as $A$ it satisfies the axioms of being the type of structure in question. This is unfortunaetly not quite as easy in category theory in its fullest generality, the underlying objects which form a category are not sets with structure, they may be far more abstract and do not contain elements. Subobjects and quotients are not as obvious in the general category as it for groups and vector spaces. In practice one often works with categories in which the objects have underlying sets and maps have kernels, images, cokernels, et cetera. We will explore when we can treat categories as if they have elements in each object later.

## Categories

We now introduce the titular concept, the category. We want to abstract the features which allow us to study structures such as groups, vector spaces, rings, module, algebras, sets, et cetera. The idea is that a category is a collection of objects share the same type of structure and a collection of morphisms between them. For a category of sets we would like to have the sets as objects and maps which are just the basic functions of sets. For a category of groups we want a collection of groups and a collection of group homomorphisms. We do however want to ensure that we always have the idenity maps for each object in the category.

::: {#def-category}
## Category
A category $\mathcal{C}$ consists of a pair of classes $(\Ob, \Hom)$, a pair of class functions $\dom, \cod:\Hom\to \Ob$ and a class function
$$\circ: \Hom\times_{\Ob}\Hom\to \Hom$$
where $$\Hom\times_{\Ob}\Hom:=\{(\psi,\phi)\in \Hom\times \Hom\,\vert\,\dom \psi=\cod \phi\}$$
which satisfy the following axioms. Note that here we write $\psi\circ \phi$ instead of $\circ (\psi, \phi)$.

::: {.axioms}
#. For any two elements $(\psi,\phi)\in \Hom\times_{\Ob} \Hom$ we have $\dom (\psi\circ\phi)=\dom \phi$ and $\cod (\psi\circ\phi)=\cod \psi$.
#. For elements $\phi, \psi, \rho\in \Hom$ such that $\psi\circ\phi$ and $\rho\circ \psi$ are well defined we have that
$$\rho\circ (\psi\circ\phi)=(\rho\circ\psi)\circ \phi$$
#. For each $X\in \Ob$ there exists an element $\id_X\in \Hom$ with $\dom \id_X = \cod \id_X=X$ such that we have
$$\id_X\circ \phi= \phi$$
for all $\phi\in\Hom$ with $\cod \phi = X$, and
 $$\psi\circ \id_X=\psi$$
for all $\psi\in\Hom$ with $\dom \psi = X$.
:::

:::

We refer to the members of $\Ob$ as objects and members of $\Hom$ as morphisms. We tend to abuse the notation here and write $X\in \mathcal{C}$ for an object $X$. Additionally, we often give morphisms $\phi :X\to Y$, in the same manner as for the structures which we are use to, to mean that $\phi\in\Hom$, and $X$ and $Y$ are objects such that $\dom\phi = X$ and $\cod\phi =Y$. When we are working with multiple categories we might distinguish the object and morphism classes by subscripts, such as $\Ob_\mathcal{C}$ for the object class of $\mathcal{C}$ or $\Hom_\mathcal{A}$ for the morphism class of $\mathcal{A}$. For any two objects $X,Y\in \Ob$ we denote the class of morphisms with domain $X$ and codomain $Y$ by $\Hom_{\mathcal{C}}(X,Y)$. The definition above differs from that given by [@EilMac45],[^defdiff] here i favour a modified version of the definition given by [@Lein14] as it avoids having to deal with the, in my opinion, convoluted handling of domain and codomain, and identities. The presentation which I have given here is more in line with what is usually presented in an introduction to category theory, in my experience.

### Inverses and Isomorphisms

For each object $X\in \mathcal{C}$ we call the morphism $\id_X:X\to X$ the identity at $X$. In the same manner which one would prove that the group identity is unique we of course obtain that the identity at each object is unique. We give the definition of inverse morphisms below, these are just like inverses for maps of sets, where we want cancellation of morphisms to produce the identity morphism. Note that we do not always have inverses.

::: {#def-inversemorphism}
## Inverse morphism
Let $\mathcal{C}$ be a category and $\phi :X\to Y$ a morphism. Then we say that a morphism $\psi: Y\to X$ is called a right inverse of $\phi$ if $\phi\circ \psi=\id_Y$ and it is called a left inverse of $\phi$ if $\phi\circ\psi=\id_X$. Furthermore, $\psi$ is called an inverse of $\phi$ if it is both a right and left inverse of $\phi$. 
:::

We denote the inverse of $\phi$, when it exists, by $\phi^{-1}$. A natural question arises, if an inverse is a morphism which is both a right and a left inverse, is it possible to have a morphism which admits both a left and right inverse which are distrinct? Of course not, below we present the same argument that one might find for an algebraic structure in which we can have left and right inverses and an associative binary operation.

::: {#prp-leftrightinverse}
Let $\phi:X\to Y$ be a morphism which admits a right inverse $\psi:Y\to X$, and a left inverse $\rho:Y\to X$. Then $\psi=\rho$.
:::

::: {.proof}
We simply use the associativity of composition and the right and left inverseness.
$$
\begin{aligned}
\rho &=\rho\circ\id_X=\rho\circ(\phi\circ\psi)\\
&=(\rho\circ\phi)\circ\psi=\id_Y\circ\psi=\psi
\end{aligned}$$
:::

Note that if $\phi$ admits a left inverse $\psi$ then $\phi$ is a right inverse of $\psi$ and conversely, if $\phi$ admits a right inverse $\psi$ then $\phi$ is a left inverse of $\psi$. Likewise, if $\phi$ admits an inverse $\psi$ then $\psi$ admits $\phi$ as an inverse, and so we can say that $\phi$ and $\psi$ are mutually inverse to each other. As hinted in the group theoretic introduction, inverses give us our category theoretic definition for an isomorphism. Isomorphisms play a major role in every field, and we often classify objects up to isomorphism, as they encode objects which are essentially the same.

::: {#def-isomorphism}
## Isomorphism
Let $\mathcal{C}$ be a category. We say that a morphism $\phi\in\Hom_\mathcal{C}$ is an isomorphism if there is a morphism $\psi:\cod \phi\to \dom \phi$ such that $\psi$ is an inverse of $\phi$
:::

We tend to denote that two objects $X$ and $Y$ are isomorphic by writing $X\cong Y$. The reason that I write that two isomorphic objects are essentially the same is that their maps correspond one-to-one, with a satisfactory structure.[^esssame] If $X\cong Y$ through the isomorphism $\rho:X\to Y$, and $\phi:X\to Z$ is a morphism, then there is a morphism $\hat{\phi}:Y\to Z$ given by $\phi\circ\rho^{-1}$. Similarly, for any morphism $\psi:Y\to Z$ we have a morphism $\hat{\psi}:X\to Z$ given by $\psi\circ \rho$.

::: {#prp-hombijofisom}
Let $X\neq Y$ be isomorphic objects in a category $\mathcal{C}$, and let $\Hom_{\mathcal{C}} X$ denote the class 
$$\Hom_{\mathcal{C}} X:=\{\phi\in \Hom_{\mathcal{C}}\,\vert\,\dom\phi =X \vee \cod\phi=X\}$$
Then we obtain that there is a class bijection $\Hom_{\mathcal{C}} X \simeq \Hom_{\mathcal{C}} Y$.
:::

::: {.proof}
Let $\rho: X\to Y$ be an isomorphism between $X$ and $Y$, it admits the inverse $\rho^{-1}$ by definition. Note that we can express $\Hom_{\mathcal{C}} X$ as the union $\Hom_{\operatorname{in}} X\cup \Hom_{\operatorname{out}} X \cup \End_{\mathcal{C}} X\cup \Hom_{\mathcal{C}}(X,Y) \cup \Hom_{\mathcal{C}}(Y,X)$ where
$$\Hom_{\operatorname{in}} X:=\{\phi\in \Hom\,\vert\,\cod\phi=X\wedge \dom\phi\not\in \{X,Y\}\}$$
$$\Hom_{\operatorname{out}} X:=\{\phi\in \Hom\,\vert\,\dom\phi =X\wedge\cod\phi\notin\{X,Y\} \}$$
and
$$\End_{\mathcal{C}} X :=\{\phi \in \Hom\,\vert\, \dom\phi=\cod\phi=X\}$$
This is clearly a disjoint union of classes, therefore this describes a proper decomposition of all morphisms *touching* $X$. Similarly we decompose $\Hom_{\mathcal{C}}Y=\Hom_{\operatorname{in}} Y\cup \Hom_{\operatorname{out}} Y \cup \End_{\mathcal{C}} Y\cup \Hom_{\mathcal{C}}(X,Y) \cup \Hom_{\mathcal{C}}(Y,X)$.

Now we have a class map $F_{\operatorname{out}}:\Hom_{\operatorname{out}}Y\to \Hom_{\operatorname{out}}X$ defined by $[\phi:Y\to Z]\mapsto\phi\circ \rho$.
Similarly, we define $G_{\operatorname{out}}:\Hom_{\operatorname{out}}X\to \Hom_{\operatorname{out}}Y$ by sending $[\phi:X\to Z]\mapsto\phi\circ\rho^{-1}$. Now let $\phi\in\Hom_{\operatorname{out}}X$, then
$$\begin{aligned}
F_{\operatorname{out}}(G_{\operatorname{out}}(\phi)) &= F_{\operatorname{out}}(\phi\circ \rho^{-1})=\phi\circ\rho^{-1}\circ\rho\\
&=\phi\circ(\rho^{-1}\circ\rho)=\phi\circ\id_X=\phi
\end{aligned}$$
On the other hand, for any $\phi\in \Hom_{\operatorname{out}}Y$ we have
$$\begin{aligned}
G_{\operatorname{out}}(F_{\operatorname{out}}(\phi)) &= G_{\operatorname{out}}(\phi\circ \rho)=\phi\circ\rho\circ\rho^{-1}\\
&=\phi\circ(\rho\circ\rho^{-1})=\phi\circ\id_Y=\phi
\end{aligned}$$
By such, $F_{\operatorname{out}}$ and $G_{\operatorname{out}}$ are mutually inverse. In the same manner we have that there are class maps $F_{\operatorname{in}}:\Hom_{\operatorname{in}}Y\to \Hom_{\operatorname{in}}X$ defined by $\phi\to \rho^{-1}\circ \phi$ and $G_{\operatorname{in}}:\Hom_{\operatorname{in}}X\to \Hom_{\operatorname{in}}Y$ defined by $\phi\to \rho\circ \phi$ such that $F_{\operatorname{in}}$ and $G_{\operatorname{in}}$ are mutually inverse.

Now consider the maps $I:\End_\mathcal{C} X\to \End_\mathcal{C} Y$ defined by $[\phi:X\to X]\mapsto\rho\circ\phi\circ\rho^{-1}$ and $J:\End_\mathcal{C} Y\to \End_\mathcal{C} X$ defined by $[\phi:Y\to Y]\mapsto\rho^{-1}\circ\phi\circ\rho$. Then we have for any $\phi\in \End_{\mathcal{C}}X$
$$\begin{aligned}
J(I(\phi)) &=\rho^{-1}\circ I(\phi)\circ \rho\\
&= \rho^{-1}\circ(\rho\circ \phi\circ\rho^{-1})\circ \rho=(\rho^{-1}\circ\rho)\circ \phi\circ(\rho^{-1}\circ \rho)\\
&=\id_X\circ\phi\circ\id_X=\phi
\end{aligned}
$$
A similar calculation gives $I(J(\phi))=\phi$, for any $\phi\in\End_\mathcal{C} Y$.

Now we obtain a piecewise class map $\Phi: \Hom_\mathcal{C}X\to \Hom_\mathcal{C}Y$ defined by
$$\phi\mapsto\begin{cases}
\phi & \phi\in \Hom_\mathcal{C} (X,Y)\cup\Hom_\mathcal{C}(Y,X)\\
G_{\operatorname{out}} (\phi) & \phi\in\Hom_{\operatorname{out}}X\\
G_{\operatorname{in}}(\phi) & \phi\in \Hom_{\operatorname{in}}X\\
I(\phi) & \phi\in \End_{\mathcal{C}}X
\end{cases}$$
Furthermore, we define the map $\Psi: \Hom_\mathcal{C}Y\to \Hom_\mathcal{C}X$ by
$$\phi\mapsto\begin{cases}
\phi & \phi\in \Hom_\mathcal{C} (X,Y)\cup\Hom_\mathcal{C}(Y,X)\\
F_{\operatorname{out}} (\phi) & \phi\in\Hom_{\operatorname{out}}Y\\
F_{\operatorname{in}}(\phi) & \phi\in \Hom_{\operatorname{in}}Y\\
J(\phi) & \phi\in \End_{\mathcal{C}}Y
\end{cases}$$
From the constructions of $F_{\operatorname{out}}, G_{\operatorname{out}}, F_{\operatorname{in}}, G_{\operatorname{in}}, I$ and $J$ we obtain that $\Phi$ and $\Phi$ are mutually inverse.
:::

### Fundamental Examples

We now turn to some simple examples of categories to solidify the definitions presented in this brief introduction. Before reading these, contemplate for a moment the different structures you have encountered previously. Are they sets with added structure? What structural properties do the maps possess, and how do they compose with each other? What do the identities look like and when do morphisms admit inverses?

Often when we are constructing categories we choose first our appropriate definition of isomorphism, and then we work towards finding which definition of morphism yields these isomorphism. For example, for topological spaces we think of two spaces as isomorphic if there is a homeomorphism between them, that is a bijection which is continuous in both directions. Then we should restrict the class of morphisms to include only continuous maps. If we were to include non-continuous maps then we could have a non-continuous bijection of sets which is invertible and hence an isomorphism which is not a homeomorphism. Similarly, we consider two groups as isomorphic if there is a group isomorphism between them (that is a bijective map respecting group operations). If the set of morphisms is given by all group homomorphisms, then the isomorphism are precisely the group isomorphisms. However, if we were to include all maps we would have an invertible map which is not a group homorphism. For example, consider the group $\ZZ_4=\{0,1,2,3\}$, the group $\ZZ_2\times \ZZ_2={(0,0), (1,0), (0,1), (1,1)}$, and a map $\phi:\ZZ_4\to \ZZ_2\times \ZZ_2$ defined by 
$$g\mapsto\begin{cases}
(1,1) & g=0\\
(0,1) & g=1\\
(1,0) & g=2\\
(0,0) & g=3
\end{cases}$$
Then $\phi$ is a bijective map, however it is not a group homomorphism as $\phi(0\ast 1)=\phi(1)=(0,1)$ and $\phi(0)\ast\phi(1)=(1,1)\ast (0,1)=(1,0)$, indeed no group isomorphism exists. The two groups are not isomorphic as groups but their underlying sets are, by such the wrong choice of definition for morphism will yield undesired isomorphisms, and hence the wrong critera for object equivalence.



### Unfinished

::: {#exm-groupcategory}
Let $G$ be a group, consider the category $\mathcal{G}$ with one object $X$ and for each element $g\in G$ we have an automorphism $\phi_g:X\to X$ whose inverse is given by $\phi_{g^{-1}}$ such that for each $g,h\in G$ we have $\phi_h\circ\phi_g=\phi_{g\ast h}$. This is a complete encoding of the group as a category, all possible group multiplications are given by successive compositions of morphisms, the group identity is given by the identity morphism, and composition is associative. Given a subgroup $H$ of $G$ we can form the category $\mathcal{H}$ from $\mathcal{G}$ by removing the morphisms corresponding to elements which are in $G$ but not in $H$.
:::

::: {#def-discretecategory}
## Discrete category
A category in which the only morphisms are the identity morphisms is called discrete.
:::

::: {#def-emptycategory}
## Empty category
The category with no objects and no morphisms is called the empty category.
:::

::: {#def-subcategory}
## Subcategory
Let $\mathcal{C}$ be a category. We say that a category $\mathcal{D}$ is a subcategory of $\mathcal{C}$ if $\Ob_\mathcal{D}$ is a subclass of $\Ob_{\mathcal{C}}$, $\Hom_\mathcal{D}$ is a subclass of $\Hom_{\mathcal{C}}$ with $$\dom_\mathcal{D}=\dom_\mathcal{C}\vert_{\Hom_\mathcal{D}}$$
$$\cod_\mathcal{D}=\cod_\mathcal{C}\vert_{\Hom_\mathcal{D}}$$
$$\circ_{\mathcal{D}}=\circ_{\mathcal{C}}\vert_{\Hom_\mathcal{D} \times_{\Ob_{\mathcal{D}}}\Hom_{\mathcal{D}}}$$ and $\id_X^{\mathcal{D}}=\id_X^{\mathcal{C}}$ for all $X\in\mathcal{D}$.
:::

Equivalently, given a subclass $\Ob_\mathcal{D}$ of $\Ob_\mathcal{C}$ and a subclass $\Hom_{\mathcal{D}}$ of $\Hom_\mathcal{C}$ we have a subcategory $\mathcal{D}$ with object class $\Ob_{\mathcal{D}}$ and morphism class $\Hom_{\mathcal{D}}$ if the image of $\Hom_{\mathcal{D}}\times_{\Ob_\mathcal{C}} \Hom_{\mathcal{D}}$ under $\circ_{\mathcal{C}}$ is in $\Hom_{\mathcal{D}}$, and $\id_X\in\Hom_{\mathcal{D}}$ for all $X\in \mathcal{D}$. That is to say that $\mathcal{D}$ is closed under composition and identities. We have the following obvious classifications of subcategories which quantify how complete their data is.

::: {#def-fullandwide}
## Full and wide subcategories
Let $\mathcal{D}$ be a subcategory of $\mathcal{C}$. Then $\mathcal{D}$ is called a full subcategory if for each pair of objects $X$ and $Y$ in $\mathcal{D}$ we have that $\Hom_\mathcal{D}(X,Y)=\Hom_\mathcal{C}(X,Y)$. We say that the subcategory $\mathcal{D}$ is wide if $\Ob_\mathcal{D}=\Ob_{\mathcal{C}}$.
:::

Roughly speaking fullness of a subcategory means that it inherits all possible morphisms for the objects from the supercategory, and wideness means that we have all objects of the supercategory. Clearly a full and wide subcategory is just the supercategory itself.

::: {#exm-exmsubcat}
#. Let $\mathcal{C}$ be a category, then we can form a subcategory $\mathcal{D}\subseteq\mathcal{C}$ by letting $\mathcal{D}$ be the discrete category with objects $\Ob_{\mathcal{C}}$, this is a wide subcategory.
#. Consider the category of groups $\Grp$, then the category of Abelian Groups $\AbGrp$ is a full subcategory of $\Grp$.
#. For the category of vector spaces $\Vect$ we can construct a full subcategory whose objects are the finite dimensional vector spaces.
#. For any category $\mathcal{C}$ and an object $X\in \mathcal{C}$ we can create the full subcategory $\mathcal{C}_X$ consisting all objects $Y$ for which there is a morphism $\phi\in \Hom_\mathcal{C}$ with $Y=\dom\phi$ and $X=\cod \phi$ or $Y=\cod \phi$ and $X=\dom \phi$.
#. Consider [@exm-groupcategory] and let $H$ be a subgroup of $G$. Then the corresponding category $\mathcal{H}$ is a subcategory of $\mathcal{G}$. This subcategory is obviously wide.
:::

[^defdiff]: In particular the domain and codomain maps do not appear in the definition from Eilenberg and MacLane, and the axioms instead give rise to a result which states that each morphim $\phi$ admits exactly one identity $\id_X$ such that $\phi\circ\id_X$ is defined, and exactly one identity $\id_Y$ such that $\id_Y\circ\phi$ is well defined. Then $X$ is the domain and $Y$ is the codomain.

[^esssame]: The bijectivity is not the only important part and does not by itself imply that the two objects are essentially the same. The picture which we present here is incomplete, indeed these $\Hom$ classes can be bijective even if the objects are not isomorphic. However, the following proposition does give us some insight on how the morphisms of two isomorphic objects correspond with each other. The structure of equivalence comes from the fact that something called a natural isomorphism arises, however this is something which we will explore later. A natural transformation is an object that is outlined in the introduction in [@EilMac45] which partially motivates the development of category theory.